[package]
name = "egui_tiles_ext"
version = "0.2.0"
edition = "2024"

[dependencies]
eframe = { version = "0.32.0", default-features = false }
egui = { version = "0.32.0", default-features = false }
egui_tiles = "0.13.0"
